
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author gabri
 */
public class TabelaCarro extends javax.swing.JFrame {

    Carro Car = null;
    ArrayList<Carro> Carro = new ArrayList<>();

    public TabelaCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPainel = new javax.swing.JPanel();
        Marca = new java.awt.TextField();
        Modelo = new java.awt.TextField();
        AnoDeFabricacao = new java.awt.TextField();
        Cor = new java.awt.TextField();
        jMarca = new javax.swing.JLabel();
        jMarca1 = new javax.swing.JLabel();
        jAnoDeFabricacao = new javax.swing.JLabel();
        jCor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jConsultar = new javax.swing.JButton();
        jCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPainel.setBackground(new java.awt.Color(204, 255, 204));
        JPainel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        JPainel.setForeground(new java.awt.Color(0, 0, 0));

        Marca.setBackground(java.awt.SystemColor.activeCaption);
        Marca.setFont(new java.awt.Font("Dubai Medium", 2, 14)); // NOI18N
        Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaActionPerformed(evt);
            }
        });

        Modelo.setBackground(java.awt.SystemColor.activeCaption);
        Modelo.setFont(new java.awt.Font("Dubai Medium", 2, 14)); // NOI18N
        Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloActionPerformed(evt);
            }
        });

        AnoDeFabricacao.setBackground(java.awt.SystemColor.activeCaption);
        AnoDeFabricacao.setFont(new java.awt.Font("Dubai Medium", 2, 14)); // NOI18N
        AnoDeFabricacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoDeFabricacaoActionPerformed(evt);
            }
        });

        Cor.setBackground(java.awt.SystemColor.activeCaption);
        Cor.setFont(new java.awt.Font("Dubai Medium", 2, 14)); // NOI18N
        Cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorActionPerformed(evt);
            }
        });

        jMarca.setForeground(new java.awt.Color(0, 0, 0));
        jMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMarca.setText("Modelo");

        jMarca1.setForeground(new java.awt.Color(0, 0, 0));
        jMarca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMarca1.setText("Marca");

        jAnoDeFabricacao.setForeground(new java.awt.Color(0, 0, 0));
        jAnoDeFabricacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAnoDeFabricacao.setText("AnoDeFabricacao");

        jCor.setForeground(new java.awt.Color(0, 0, 0));
        jCor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCor.setText("Cor");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crie Seu Cadastro");

        jConsultar.setBackground(new java.awt.Color(51, 255, 0));
        jConsultar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jConsultar.setForeground(new java.awt.Color(0, 0, 0));
        jConsultar.setText("Consultar");
        jConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsultarActionPerformed(evt);
            }
        });

        jCadastrar.setBackground(new java.awt.Color(51, 255, 0));
        jCadastrar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jCadastrar.setText("Cadastrar");
        jCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPainelLayout = new javax.swing.GroupLayout(JPainel);
        JPainel.setLayout(JPainelLayout);
        JPainelLayout.setHorizontalGroup(
            JPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPainelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AnoDeFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(JPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPainelLayout.createSequentialGroup()
                        .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPainelLayout.createSequentialGroup()
                        .addComponent(jMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPainelLayout.createSequentialGroup()
                        .addComponent(Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(JPainelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jAnoDeFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCor, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPainelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(JPainelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(JPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPainelLayout.createSequentialGroup()
                        .addComponent(jConsultar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPainelLayout.createSequentialGroup()
                        .addComponent(jCadastrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        JPainelLayout.setVerticalGroup(
            JPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPainelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(JPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jMarca)
                    .addComponent(jMarca1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(JPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAnoDeFabricacao)
                    .addComponent(jCor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnoDeFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jConsultar)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaActionPerformed

    private void ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeloActionPerformed

    private void AnoDeFabricacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoDeFabricacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnoDeFabricacaoActionPerformed

    private void CorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorActionPerformed

    private void jConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsultarActionPerformed
        String str = "";
    for (int i = 0; i < Carro.size(); i++) {
        str += "\nMarca: " + Carro.get(i).getMarca();
        str += "\nModelo: " + Carro.get(i).getModelo();
        str += "\nAno de Fabricação: " + Carro.get(i).getAnoDeFabricacao();
        str += "\nCor: " + Carro.get(i).getCor();
        }// TODO add your handling code here:
        
        JOptionPane.showMessageDialog(rootPane, str);
    }//GEN-LAST:event_jConsultarActionPerformed

            
    private void jCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastrarActionPerformed
        Car = new Carro();
        Car.setMarca(Marca.getText());
        Car.setModelo(Modelo.getText());
        Car.setAnoDeFabricacao(Integer.parseInt(AnoDeFabricacao.getText()));
        Car.setCor(Cor.getText());

        Carro.add(Car);

        JOptionPane.showMessageDialog(rootPane, Car.getModelo() + " *cadastrado com sucesso");
    }//GEN-LAST:event_jCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField AnoDeFabricacao;
    private java.awt.TextField Cor;
    private javax.swing.JPanel JPainel;
    private java.awt.TextField Marca;
    private java.awt.TextField Modelo;
    private javax.swing.JLabel jAnoDeFabricacao;
    private javax.swing.JButton jCadastrar;
    private javax.swing.JButton jConsultar;
    private javax.swing.JLabel jCor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jMarca;
    private javax.swing.JLabel jMarca1;
    // End of variables declaration//GEN-END:variables
}
